camera_url: "rtsp://admin:smartspaces2019@172.20.3.183:554"
zones:
  - name: "Zone 1"
    color: [0, 0, 255]
    points:
      - [0, 0]
      - [205, 0]
      - [205, 1080]
      - [0, 1080]

  - name: "Zone 2"
    color: [0, 255, 0]
    points:
      - [205, 0]
      - [205, 570]
      - [630, 473]
      - [630, 0]
  - name: "Zone 3"
    color: [255, 0, 0]
    points:
      - [630, 0]
      - [630, 470]
      - [1260, 440]
      - [1260, 100]
  - name: "Zone 4"
    color: [ 255, 255, 0 ]
    points:
      - [1800, 100]
      - [1775, 975]
      - [1920, 1000]
      - [1920, 20]
  - name: "Zone 5"
    color: [ 0, 255, 255]
    points:
    - [ 190, 785 ]
    - [ 190, 1920 ]
    - [ 1775, 1920 ]
    - [ 1775, 785 ]
confidence: 0.5
show_labels: true